version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: inventory-management-web
    hostname: inventory-management-web
    container_name: inventory-management-web
    volumes:
      - ./:/var/www/html
      - ./docker/local/etc/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - db
    ports:
      - "80:80"
    networks:
      - default
  db:
    image: mysql:5.7
    hostname: inventory-management-db
    container_name: inventory-management-db
    labels:
      SERVICE_NAME: inventory-management-db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventory-management_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    command: '--sql-mode=""'
    networks:
      - default
